### ISSUE TITLE
无法添加

### ISSUE THREAD

**Issue by 961739124** [iamhyc/Aigis#1]
试了一下github的两步验证，扫码的时候没有反应

**Comment by iamhyc** [comment]
可能是 issuer / name 段缺失，可以在解析的URL里手动添加下，我只验证了Aegis导出的二维码可以正确添加。下个测试版本修正 🤣

**Comment by 961739124** [comment]
> 可能是 issuer / name 段缺失，可以在解析的URL里手动添加下，我只验证了Aegis导出的二维码可以正确添加。下个测试版本修正 🤣

这个尝鲜版只有扫码😹和github的版本不同步吗

**Comment by iamhyc** [comment]
> > 可能是 issuer / name 段缺失，可以在解析的URL里手动添加下，我只验证了Aegis导出的二维码可以正确添加。下个测试版本修正 🤣
> 
> 这个尝鲜版只有扫码😹和github的版本不同步吗

蹭了下 Aegis 的名字，功能都是自己从头写的，现在密钥都是明文存的😂

**Comment by 961739124** [comment]
> > > 可能是 issuer / name 段缺失，可以在解析的URL里手动添加下，我只验证了Aegis导出的二维码可以正确添加。下个测试版本修正 🤣
> > 
> > 
> > 这个尝鲜版只有扫码😹和github的版本不同步吗
> 
> 蹭了下 Aegis 的名字，功能都是自己从头写的，现在密钥都是明文存的😂

哈哈哈

**Comment by iamhyc** [comment]
@961739124 Hi，新的测试版本 v0.2.1 已上架，可以试下问题是否解决。

**Comment by 961739124** [comment]
> @961739124 Hi，新的测试版本 v0.2.1 已上架，可以试下问题是否解决。

解决了
