### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by JOJO30317** [iamhyc/Aigis#10]
1. 增加备份恢复功能；
2. 增加点击码显示并复制，其他码隐藏；
3. 增加进入人脸或指纹验证的功能，可配置开启或关闭

**Comment by iamhyc** [comment]
感谢建议！这些都在规划中，下一版本得先把密钥加密保存下 😂

**Comment by iamhyc** [comment]
需求1 3目前（v0.2.5）已实现，需求2在 #16 中被提及，之后使用该 issue 追踪；此 issue 至此关闭，感谢反馈！
