### ISSUE TITLE
新版本0.2.2云厂商图标不显示

### ISSUE THREAD

**Issue by yakexi007** [iamhyc/Aigis#11]
添加了aws 阿里云 ucloud google的动态码，目前只有google的显示一个G图标，其他厂商显示空白。是不是有些厂商图标还未适配。

**Comment by iamhyc** [comment]
目前为了满足元服务大小要求，只封装了一些~~我自己~~常用的 icon，且issuer字段和icon名字严格匹配才加载。

预计下个版本（v0.3.0）解决密钥安全问题之后，顺便做下完善下icon匹配，允许用户导入 aegis icon package。

**Comment by iamhyc** [comment]
@yakexi007 Hi，目前 v0.2.6 版本已上架测试专区，支持导入Aegis格式图标包，以及默认自绘制图标。
