### ISSUE TITLE
MatePadpro 11 2024完全不可用

### ISSUE THREAD

**Issue by RamenRa** [iamhyc/Aigis#14]
无论是收动输入还是扫码都无法正常使用，扫码能调用相机但是并没有成功导入信息。手动输入按钮点击后没有任何弹窗

软件版本：5.0.0.102 (SP3C00E73R1P13patch05)Beta2

**Comment by iamhyc** [comment]
手机上是正常的，我这边没有平板，也没法验证；晚些时候我在模拟器里试一下。

**Comment by iamhyc** [comment]
如果之前有使用旧版本（≤0.2.2），可以试下在系统设置“应用和元服务”里完全删除后，重新安装试下。

或者，也许和“元服务数据同步”有关，可以试试在 Aigis主页面> 右上角设置 > 元服务数据同步 里暂时关掉同步。

**Comment by RamenRa** [comment]
我已重新安装没有起到任何作用。Aigis主页面的右上角只有一个关闭按钮和一个聚合了“从我的服务中移除”、“卡片”、“设置”的按钮。没有找到“元服务数据同步”的按钮

**Comment by iamhyc** [comment]
> 我已重新安装没有起到任何作用。Aigis主页面的右上角只有一个关闭按钮和一个聚合了“从我的服务中移除”、“卡片”、“设置”的按钮。没有找到“元服务数据同步”的按钮

就在那个“设置”里面。

现在一个猜想是，bindsheet 在 平板上 和 手机横屏 行为不一致，所以没有正常弹出；可以试下 悬浮小窗 是否正常？

**Comment by RamenRa** [comment]
* 使用悬浮小窗没有效果问题依然存在。
* 点击‘设置’后，只有‘管理’和‘用户协议’、‘隐私声明’。继续点击‘管理’可选项只有‘移除元服务’、‘通知’、‘查看详细访问记录’。没有‘元服务数据同步’

**Comment by iamhyc** [comment]
> * 使用悬浮小窗没有效果问题依然存在。
> 
>     * 点击‘设置’后，只有‘管理’和‘用户协议’、‘隐私声明’。继续点击‘管理’可选项只有‘移除元服务’、‘通知’、‘查看详细访问记录’。没有‘元服务数据同步’

那看来平板和手机API可能不一致，明明都是5.0系统……看下还有没有其他平板用户反馈吧，我这边大概晚上在模拟器上测下。

**Comment by qicfan** [comment]
我的Mate 60 Pro也没有，貌似这个功能只给P70上了，所以我升级5.0也没丢数据。

**Comment by qicfan** [comment]
感觉这个同步功能给其他设备上的时候还会丢一波数据，建议大家提前备份。

**Comment by iamhyc** [comment]
@RamenRa Hi，目前 v0.2.5 已上架测试专区，可以试下问题是否解决；我在平板模拟器里试了下操作是正常的。

**Comment by RamenRa** [comment]
感谢大佬的回复，重新安装后似乎没有发生任何变化。我已确认版本号v0.2.5(2005)。我录制了一个26MB的[视频](https://www.123684.com/s/KxO7Vv-6dIJA)记录了当前状况。

**Comment by iamhyc** [comment]
> 感谢大佬的回复，重新安装后似乎没有发生任何变化。我已确认版本号v0.2.5(2005)。我录制了一个26MB的[视频](https://www.123684.com/s/KxO7Vv-6dIJA)记录了当前状况。

感谢反馈，您可以删掉该视频以避免隐私泄露。

现在的情况是 平板系统 和 模拟器系统 行为不一致，我只能去问下客服了；下一版本（v0.2.6）我会增加个开关，允许跳过确认直接添加条目，以保证基础功能可以使用。

**Comment by iamhyc** [comment]
@RamenRa Hi，目前 v0.2.6 版本已上架测试专区，设置项里增加了 “添加令牌时无需确认”，可以试下是否缓解平板使用问题。

关于编辑页面不弹出的问题，目前应该还没解决，下个版本会继续探索解决方案……

**Comment by RamenRa** [comment]
@iamhyc 安装0.2.6后打开‘添加令牌时无需确认’开关。通过扫码添加验证码，发现没有任何条目被添加，和0.2.5一样的情况。

**Comment by RamenRa** [comment]
@iamhyc 扫描上面提供的二维码情况也一样，没有任何条目被添加。（我还尝试了使用aegis扫描，上面的图报错呢？测试的二维码都是aegis导出的‘兼容Google身份验证器的二维码’）

**Comment by iamhyc** [comment]
@RamenRa Hello，今天上架了 v0.2.7 版本，根据审核反馈，matepad pro测试通过（但没说是什么型号），可以再试试

![image](https://github.com/user-attachments/assets/8d56bf50-d4d0-4dab-bb12-2f83af4099bf)

**Comment by iamhyc** [comment]
> @iamhyc 可以手动导入了，基础使用已经没有问题。我是扫描上方提供的二维码然后修改参数导入的，但这样好像不能自选图标了。

目前图标匹配，只会匹配第一次打开编辑时的“服务商”名字，后续编辑不会动态更新；需要先保存一次，再打开编辑，重新触发图标匹配。
也可以在设置里打开“启用手动输入”，然后主界面右下角圆圈会变成“+”号，点“解析URI”后直接点确定会弹出编辑框，这样至少不用扫描二维码了。

图标动态匹配的问题，之后会修；导入的话，目前只支持“otpauth://”内容，google强行推 protobuf 太霸道了不是很想用；
平板使用上没有问题的话，这个issue就暂时关闭了，感谢反馈！
