### ISSUE TITLE
🚀[Feature Request] 手动刷新按钮

### ISSUE THREAD

**Issue by Gn3po4g** [iamhyc/Aigis#15]
可以在点击显示digit之后的右侧添加一个手动刷新按钮。
比如这个位置
![图片](https://github.com/user-attachments/assets/36b7da48-777d-4e8b-907b-415ba418c114)

有时候差几秒要过期又不想等的时候可以用。

另外项目非常nice，期待后续优化😊

**Comment by iamhyc** [comment]
感谢支持！目前首页（几乎）照搬 Aegis Authenticator 设计，暂时没有添加额外按钮的计划。

**Comment by Gn3po4g** [comment]
明白。现在先把功能完成，UI优化还得搁置一会😂

**Comment by JOJO30317** [comment]
一般服务器都支持一个码60秒生效，30秒生成一次，这样即使刚刚过期，仍然可以使用，不需要等待下一个码。

**Comment by Gn3po4g** [comment]
> 一般服务器都支持一个码60秒生效，30秒生成一次，这样即使刚刚过期，仍然可以使用，不需要等待下一个码。

这样啊，我记得之前用过一个TOTP软件有刷新功能，以为变了就不能用了

**Comment by iamhyc** [comment]
@Gn3po4g 目前 v0.6.0 已上架，可以在设置中启用“预览下一个令牌”；该功能在时间剩余5s时（进度条走到issuer图标右侧边缘），会同时展示下一个令牌。

从 v0.6.0 版本之后，本元服务暂时停止向AGC提交应用更新，直到鸿蒙应用运营方改变态度。
