### ISSUE TITLE
添加了Steam令牌后令牌显示乱码

### ISSUE THREAD

**Issue by flycat233** [iamhyc/Aigis#19]
令牌显示XXXX DEF FINEXXX之类的
二次刷新后会出现类似DVC4V之类的 验证码，但是输入后提示错误

**Comment by iamhyc** [comment]
大概是没有即时刷新，这个之后还需要修正；而且目前 steam secrets 没有做base64到base32的重新编码，直接粘贴进去结果可能是错的。

**Comment by flycat233** [comment]
我猜到应该是undefined 🤣Steam令牌的话应该是纯数字吧，拜托请尽快更新！

**Comment by tylertiger** [comment]
纯小白  我弄了几下  好像也复现这个bug   这个需求应该蛮多人需要的  麻烦大佬了

**Comment by qicfan** [comment]
好奇一下，steam怎么使用第三方令牌应用呀，不是只能装steam应用么？

**Comment by iamhyc** [comment]
> 纯小白 我弄了几下 好像也复现这个bug 这个需求应该蛮多人需要的 麻烦大佬了

@tylertiger  这个应该是因为secret编码原因导致的：steam secret 需要先用 base64 解码，然后再用 base32 编码，然后才是TOTP secret的格式。
相关处理其实已经做好了，但是因为是和“现v0.3.0”需求一起做的，这个需求被鸿蒙API的BUG卡住了，正在和客服交互中；如果不嫌麻烦的话，可以用上述方法处理试下，或者等 v0.3.0 版本。

> 好奇一下，steam怎么使用第三方令牌应用呀，不是只能装steam应用么？

@qicfan 需要在申请token的时候，不用官方的APP而是三方工具申请，相关讨论链接如下：

- https://github.com/beemdevelopment/Aegis/issues/390
- https://github.com/stratumauth/app/wiki/Importing-from-Steam

**Comment by qicfan** [comment]
学到了，解决了大问题，希望新版本赶紧上支持steam

**Comment by tylertiger** [comment]
好的谢谢 大佬  等你的30版本   关于这个密钥我建议是下一个steam++  也就是现在Watt Toolikt绑定一下令牌  可以通过这个看属性直接看密钥

**Comment by IcedWatermelonJuice** [comment]
> > 纯小白 我弄了几下 好像也复现这个bug 这个需求应该蛮多人需要的 麻烦大佬了
> 
> @tylertiger  这个应该是因为secret编码原因导致的：steam secret 需要先用 base64 解码，然后再用 base32 编码，然后才是TOTP secret的格式。
> 相关处理其实已经做好了，但是因为是和“现v0.3.0”需求一起做的，这个需求被鸿蒙API的BUG卡住了，正在和客服交互中；如果不嫌麻烦的话，可以用上述方法处理试下，或者等 v0.3.0 版本。
> 
> > 好奇一下，steam怎么使用第三方令牌应用呀，不是只能装steam应用么？
> 
> @qicfan 需要在申请token的时候，不用官方的APP而是三方工具申请，相关讨论链接如下：
> 
> - https://github.com/beemdevelopment/Aegis/issues/390
> - https://github.com/stratumauth/app/wiki/Importing-from-Steam

已经base64 decode+base32 encode后的secret，生成的5位steam令牌也是错误的，和其他2fa的App或者python库生成的令牌不一致。

**Comment by iamhyc** [comment]
Hello 各位，目前 v0.2.7 已上架，应该修复了Steam令牌计算错误的问题；
之前如果有导入Steam密钥（shared secret）且其中含有“=”的话，需要删除后重新导入。

由于我没有Steam令牌，仅验证了从Aegis导入一个假令牌的正确性（另外内部处理了base32 base64编码的识别）；如果还有问题的话，我会继续修复。

**Comment by tylertiger** [comment]
> Hello 各位，目前 v0.2.7 已上架，应该修复了Steam令牌计算错误的问题； 之前如果有导入Steam密钥（shared secret）且其中含有“=”的话，需要删除后重新导入。
> 
> 由于我没有Steam令牌，仅验证了从 Aegis 通过二维码导入一个假令牌的正确性（另外内部处理了base32 base64编码的识别）；如果还有问题的话，我会继续修复。

尝试了一下  可以正常使用了  谢谢大佬
