### ISSUE TITLE
建议修改下名字或者其他途径增加搜索关键词

### ISSUE THREAD

**Issue by qicfan** [iamhyc/Aigis#20]
大佬，建议在名字里加入令牌、OTP等关键词，或者有没有其他途径可以实现这些关键词的搜索，目前很难让目标用户找到。
我是在尝鲜里随便翻的时候看到然后点进来才知道是啥的。

好东西应该让更多人用到:)

**Comment by iamhyc** [comment]
这个等商店更新下索引再说吧，我在 应用简介/一句话介绍 里的关键词应该够用 🤣 

应用改名字的话好像得重新备案了

**Comment by qicfan** [comment]
可能元服务和应用不太一样，我刚试了下应用可以通过名字里没有的关键词搜到，元服务必须名字里包含该关键词才行。

**Comment by iamhyc** [comment]
![图片](https://github.com/user-attachments/assets/a3a61cc6-16e5-45e0-900b-4158c60277b8)

唉不行就改名吧……
