### ISSUE TITLE
steam令牌生成错误

### ISSUE THREAD

**Issue by IcedWatermelonJuice** [iamhyc/Aigis#23]
aigis直接扫aegis中的二维码导入steam令牌。但是aigis生成的令牌不正确，和aegis、authenticator pro、pc端的steamguard生成的不一样。

**Comment by IcedWatermelonJuice** [comment]
补充，同一个steam的otpauth uri（secret已经过base64解码+base32编码），使用pyotp库直接解析也是正确的，所以应该不是uri的secret问题。

**Comment by iamhyc** [comment]
#19 已经提到了，v0.2.7已修复，请耐心等待；上架后我会在隔壁说一下。
