### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by 94run** [iamhyc/Aigis#24]
1. 主密码支持修改。
2. 设置主密码添加备注。
3. 桌面卡片支持展示单个令牌。

**Comment by 94run** [comment]
1. 主密码支持修改。
2. 设置主密码添加备注。
3. 桌面卡片支持展示单个令牌。

**Comment by iamhyc** [comment]
感谢建议！

> 1. 主密码支持修改。

计划 v0.3.0/v0.5.0 实现；

> 2. 设置主密码添加备注。

暂时没有规划，如果有现成的样例可以参考的话，可以考虑和上面的需求一起实现；

> 3. 桌面卡片支持展示单个令牌。

这个计划正式版（v1.0.0）之后再做，还没搞清楚 动态卡片 的工作机制。

**Comment by iamhyc** [comment]
Hi @94run ，目前 v0.3.0 已上架“应用尝鲜”专区，支持主密钥更改，请在导出备份数据后，再尝试该功能。

- 关于“设置主密码添加备注”，目前没有实现，如果您有好的UI建议或参考，请再新建一个 issue 跟踪进度，谢谢！

- 关于“桌面卡片支持展示单个令牌”，计划正式版（v1.0.0）之后再做，之后会添加在 Roadmap 中。（您同样可以创建一个新 issue 进行跟踪进度）
