### ISSUE TITLE
[UI] 建议增加紧凑模式和标准模式

### ISSUE THREAD

**Issue by YrracOwl** [iamhyc/Aigis#25]
UI描述：
紧凑模式下，top-margin down-margin和padding更小；
标准模式下，margin和padding更大一些；
宽松模式下，更大。

**Comment by iamhyc** [comment]
感谢反馈！预计 v1.0.0 之后再实现；打算做成根据条目数目，动态调整高度和间距的效果，同时也可以提供 紧凑/标准/宽松 的选择。

**Comment by iamhyc** [comment]
视图模式 已于 v1.0.0 实现，但是要被审核拖到 2025年了 😅 祝大家新年快乐吧 ！
