### ISSUE TITLE
建议：能否支持导入aegis等其他app的备份文件

### ISSUE THREAD

**Issue by IcedWatermelonJuice** [iamhyc/Aigis#26]
现在aigis无法导入aegis的备份文件（加密和未加密都不行），后续大佬有没有计划支持一下？或者能否支持authenticator pro导出的纯文本备份（每一行都是一个otpauth的URI）

**Comment by iamhyc** [comment]
预计在 v1.0.0 支持 Aegis 格式导入，请参照 [Roadmap](https://github.com/iamhyc/Aigis?tab=readme-ov-file#roadmap)。

当前可以使用 otpauth 二维码/URI导入；URI导入需要在设置里启用“手动输入”，且目前仅支持 单次单个URI 导入。

**Comment by zhenliangli** [comment]
我观察其他大多数 备份数据基本上都进行了二次加密备份，不太可能支持其他软件备份导入。

**Comment by iamhyc** [comment]
> 我观察其他大多数 备份数据基本上都进行了二次加密备份，不太可能支持其他软件备份导入。

@shouyong 只要实现对应的解密就可以了，让用户提供密钥；目前正在实现 Aegis 的加密备份导入（基于Scrypt密钥生成算法）。

**Comment by iamhyc** [comment]
目前 v0.6.0 已上架，支持多行 otpauth URI 链接导入，支持 Google Authenticator 导出二维码导入。

从 v0.6.0 版本之后，本元服务暂时停止向AGC提交应用更新，直到鸿蒙应用运营方改变态度。

@IcedWatermelonJuice 你可以去用隔壁的OTP软件。
