### ISSUE TITLE
建议增加令牌可选图标

### ISSUE THREAD

**Issue by flycat233** [iamhyc/Aigis#27]
可选常见图标或自行上传图标

**Comment by iamhyc** [comment]
请使用Aegis格式图标包，暂时没有计划支持上传图标。

**Comment by iamhyc** [comment]
v0.7.0 已支持编辑页面图标上传，当前仅支持小于5KB的 PNG/JPEG 图片文件。

当前时刻 v0.7.0 版本已提交应用市场上架审核，请等待应用市场更新；再次感谢反馈！
