### ISSUE TITLE
卡片中建议新增一个单图标卡片

### ISSUE THREAD

**Issue by shouyong** [iamhyc/Aigis#29]
手机桌面空间紧张，现在的查看口令卡片进去的是查看页面。存在2个问题：
1. 查看页面不能新增。
2. 查看的卡片图片太大了。

**Comment by iamhyc** [comment]
建议很好，就是没大看懂 🤣 

> 查看页面不能新增。

“查看页面”是什么？这个没看懂

> 查看的卡片图片太大了

那个 1x2 的卡片我觉得还行啊；我是放首页上，和“一键锁屏”卡片叠在一起

**Comment by iamhyc** [comment]
> > “查看页面”是什么？这个没看懂
> > > 查看的卡片图片太大了
> 
> 我测试发现， 通过【查看令牌】卡片进入，右小角的红色扫码按钮会偶尔不存在。

如果前一次使用时“按钮处于隐藏状态”，再从后台打开会保持隐藏，列表向下拉一下会恢复；这个下一版本会优化。

**Comment by iamhyc** [comment]
Hi，我重新看了一下需求，当前 单图标 卡片是不能实现的，最小的卡片是 1x2 大小。

计划之后用 令牌卡片 替代现在的入口，即可以在桌面上堆叠多个令牌卡片，支持动态刷新查看。但是现在被官方API的缺陷卡住了，还在等官方回应。

如有单图标需求，请使用隔壁的开源软件，他们那个是有**桌面图标**的：OTP令牌，https://github.com/SolidFaker/ohtotptoken

**Comment by shouyong** [comment]
数据已经倒入了，不想再次折腾了。

**Comment by iamhyc** [comment]
> 数据已经倒入了，不想再次折腾了。

@shouyong 由于AG方面歧视元服务，现在 Aigis 已申请下架，预计很快会被通过；请及时迁移您到数据到其他软件，数据迁移手段请参考首页。
