### ISSUE TITLE
使用的雷池WAF，多个雷池TOTP二维码，扫描会覆盖。

### ISSUE THREAD

**Issue by wujiops** [iamhyc/Aigis#3]
如题

**Comment by iamhyc** [comment]
目前用 issuer+name 作为索引，没有验证是否覆盖保存；预计下个版本修正。

**Comment by iamhyc** [comment]
@wujiops Hi，新的测试版本 v0.2.1 已上架，可以试下问题是否解决。

**Comment by wujiops** [comment]
编辑页面无法截图，我这里显示：服务商 Safaline CE 名称 admin 我的两个服务部署的域名和服务器不同，上述两条信息是相同的。两个二维码仍然会相互覆盖，只显示最后扫描的一条信息Safeline CE (admin)。但是我的版本仍然显示是0.2.0，怎样升级到0.2.1呢

**Comment by iamhyc** [comment]
> 编辑页面无法截图，我这里显示：服务商 Safaline CE 名称 admin 我的两个服务部署的域名和服务器不同，上述两条信息是相同的。两个二维码仍然会相互覆盖，只显示最后扫描的一条信息Safeline CE (admin)。但是我的版本仍然显示是0.2.0，怎样升级到0.2.1呢

目前v0.2.1下载量已满无法下载，可以等下明天的v0.2.2

**Comment by iamhyc** [comment]
@wujiops Hi，v0.2.2版本已推送测试专区，可以试下。

**Comment by wujiops** [comment]
扫描提示存在同名条目"Safeline CE:admin"，重命名Safeline CE为Safeline CE2可以保存，但是仍然覆盖原来的。能确认是两个TOTP二维码，因为扫描出来的两个密钥值不同。

**Comment by iamhyc** [comment]
> 扫描提示存在同名条目"Safeline CE:admin"，重命名Safeline CE为Safeline CE2可以保存，但是仍然覆盖原来的。能确认是两个TOTP二维码，因为扫描出来的两个密钥值不同。

还真的是……这次还是没测试到位；预计这周下个版本（v0.2.3）修正，感谢反馈！

**Comment by iamhyc** [comment]
@wujiops Hi，请试一下刚上架测试专区的 v0.2.3 版本，这次应该修好了

**Comment by iamhyc** [comment]
Hi，目前下载限额又满了，如果需要试用的话请在此回复，我会再加一些限额；或者可以等下月底的 v0.2.5 版本 :)

**Comment by wujiops** [comment]
你好，我的问题解决了，版本是v0.2.3🎊
