### ISSUE TITLE
同一软件，部署到不同的服务器，产生不同的二维码。扫描后改名不生效，仍然会覆盖。

### ISSUE THREAD

**Issue by wujiops** [iamhyc/Aigis#32]
之前修复的bug又复现了。具体参考issues #3

**Comment by iamhyc** [comment]
请问下是否是 v0.6.0 版本，之前版本在名称索引上引入了bug，v0.6.0版本已修正

**Comment by iamhyc** [comment]
哦不对，上面似乎说错了，这是个实现逻辑上的bug；那我尽快推个版本吧，至于审核的问题，到时候再说……

**Comment by iamhyc** [comment]
> 哦不对，上面似乎说错了，这是个实现逻辑上的bug；那我尽快推个版本吧，至于审核的问题，到时候再说……
> 
> 测试用例：
> 
>     1. 添加 "A:B" --> 再次添加 "A:B" --> 【覆盖保存】
> 
>     2. 添加 "A:B" --> 再次添加 "A:B" 并 改名为 "A:B1" --> 【新增保存】
> 
>     3. 添加 "A:B" --> 再次添加 "A:B" 并 改名为 "A1:B" --> 【新增保存】
> 
>     4. 添加 "A:B" 并修改为 "A:B1" --> 再次添加 "A:B" --> 【新增保存】
> 
>     5. 添加 "A:B1", "A:B2" --> 修改 "A:B1" 为 “A:B2” --> 【提示无法覆盖]
> 
>     6. 添加 "A:B1", "A:B2" --> 修改 "A:B2" 为 "A:B3" --> 修改 "A:B1" 为 "A:B2" --> 【修改成功】
> 
>     7. 添加 "A:B1", "A:B2" --> 修改 "A:B2" 为 "A:B3" --> 修改 "A:B1" 为 "A:B3" --> 【提示无法覆盖】

v0.6.1 版本应该已修正此问题，以上测试用例验证通过；希望没引入新的bug。

当前已提交 v0.6.1 版本至应用市场 “尝鲜专区”，让我们看看AGC的审核改过了没。

**Comment by iamhyc** [comment]
> > @wujiops Hi，当前 v0.6.1 版本已上架“应用尝鲜”专区，可以试下问题是否解决。
> 
> 问题解决了，可以优化一下覆盖提醒，现在提醒覆盖信息仍然是扫码读取的内容，我觉得扫码判断是存在的UUID后，覆盖提示信息应该读取已有的UUID对应的名称信息。
> 
> 例如：
> 
>     4. 添加 "A:B" 并修改为 "A:B1" --> 再次扫码添加 "A:B" --> 提示覆盖 "A:B1"。
> 
> 
> 以上，仅建议。👍

感谢反馈！但这个应该做不到，UUID是随机生成的，和数据内容无关。

本来是想用 “条目内容的Hash值” 作为索引，但想想似乎没有必要；如果确实有需要欢迎开一个新的 issue 提出。
