### ISSUE TITLE
5.0.0.112 SP1无法创建卡片

### ISSUE THREAD

**Issue by lixiang117423** [iamhyc/Aigis#33]
如题。

**Comment by iamhyc** [comment]
相同系统版本（Pura70Pro+）测试无法复现。
请在导出数据后，在 “设置 > 应用和元服务” 中找到 Aigis 并“移除元服务”，再通过应用市场重新安装。
如果还有问题，可以试试“应用尝鲜”中的版本（2024/12/1 开始的测试）。

昨天应用市场出了些问题，部分元服务被当作应用，推测可能与此有关。

**Comment by iamhyc** [comment]
如果当前没有问题的话，这个 issue 就先关掉了。
