### ISSUE TITLE
不同机型导入失败

### ISSUE THREAD

**Issue by 94run** [iamhyc/Aigis#34]
我从mate60pro导出到mate70pro结果会解析失败，但是这个隐私界面又不让截图

**Comment by iamhyc** [comment]
请先确认下密码是否输入正确。如果确实没错的话，那么可能是不同机器（甚至不是不同机型），HUKS 内置的密钥派生算法参数不同。

下一版本（v0.7.0）会引入 二维码分享 功能（在不设置主密钥的情况下），应该可以缓解该问题，预计下周二/周三上线。

如果这个问题普遍存在的话，v1.0.0版本会切换到默认使用 Aegis 数据库格式（使用 Scrypt 密钥派生算法），但每次导出要手动输入密码了。

**Comment by 94run** [comment]
密码没有问题的，我尝试了三次。第一次是最开始设置的密码导出导入，解析失败。第二次是修改密码后的导出导入失败。为了控制变量，第三次让两个手机保持相同的版本号，然后修改简单密码再导入依然失败。另外，是否可以接入碰一碰分享，这样似乎操作上更便利，谢谢。

**Comment by 94run** [comment]
不好意思，点错了。
密码没有问题，我一共尝试了三次：
1. 导出后导入提示解析失败。
2. 修改密码后导出导入解析失败。
3. 统一到相同的0.6版本号再次修改密码导出导入依然失败。
另外，关于不同手机导出导入，后续是否有计划接入碰一碰分享呢，谢谢。

**Comment by iamhyc** [comment]
> 密码没有问题的，我尝试了三次。第一次是最开始设置的密码导出导入，解析失败。第二次是修改密码后的导出导入失败。为了控制变量，第三次让两个手机保持相同的版本号，然后修改简单密码再导入依然失败。

那看来就是 HUKS 的问题了；鸿蒙内置了个 PBKDF2+AES256 的密钥派生算法，但 AES256 的参数不给控制，应该是和设备绑定了，导致不同设备生成的密钥是不同的。

那么从 v1.0.0 开始，会默认使用 Scrypt 密钥生成算法。但 v1.0.0 放出的时间还不确定，主要因为目前 ArkTS 的实现效率低下，预计下周用 C/Rust 实现后，尽快推进进度。

> 另外，是否可以接入碰一碰分享，这样似乎操作上更便利，谢谢。

看了下元服务不支持使用 ShareKit，不能用系统分享功能 🤣

**Comment by iamhyc** [comment]
@94run Hi，当前 v0.7.0 已上线，请从重新打开元服务以更新；在未设置主密钥时，编辑页面会显示“分享链接及二维码”，可以使用新机器扫描添加。

关于“密钥派生算法变更”的实现已完成，正在测试中，预计今晚提交审核。
但从应用市场审核这个态度来看，大概要周五才能上线……

**Comment by iamhyc** [comment]
![image](https://github.com/user-attachments/assets/74b972dd-ab74-4994-a354-9f481475413e)

唉，弱智审核，总喜欢自己加戏。

**Comment by iamhyc** [comment]
@94run Hi，已经和客服~~吵完了~~友善沟通过了；当前 v0.7.1 已上架“应用尝鲜专区”，有空的话可以试下问题是否解决。

**Comment by iamhyc** [comment]
当前 v0.7.1 已推送正式上架，此 issue 至此关闭。
