### ISSUE TITLE
数据存储问题

### ISSUE THREAD

**Issue by vinsonzou** [iamhyc/Aigis#4]
华为NEXT的元服务数据是存在本地还是服务端的呢？
昨日体验版试用了，很赞，不好的是尝鲜下架后就不能用了【未放置到桌面】，不知道是我使用问题还是本来就这样。

**Comment by iamhyc** [comment]
> 华为NEXT的元服务数据是存在本地还是服务端的呢？

目前数据保存在应用沙箱中（用户首选项），没有申请网络权限所以不会有外部连接，可以放心。
预计在 v0.3.0 版本之后，密钥全部存在TEE里，沙箱中密钥仅作为导出使用，并允许AES加密保存（AES密钥也会存在TEE里）

> 昨日体验版试用了，很赞，不好的是尝鲜下架后就不能用了【未放置到桌面】，不知道是我使用问题还是本来就这样。

感谢支持！目前元服务的入口有两个：1）负一屏点击“搜索元服务”，可以看到最近使用的元服务，2）元服务页面点击右上角“四个点”图标，可以选择添加卡片到桌面。
