### ISSUE TITLE
图标建议

### ISSUE THREAD

**Issue by vinsonzou** [iamhyc/Aigis#5]
图标如未匹配到对应厂商，可以参考Aegis使用首字母放大做默认图标，现在没有就空着很不协调。

**Comment by iamhyc** [comment]
是的，目前只做了严格匹配内置的图标；这个需求优先级会比较低，大概在 密钥加密保存 之后再做。

**Comment by ZYH919** [comment]
aegis有专门的图标包，这可以导入进去嘛？

**Comment by iamhyc** [comment]
Hello，各位，目前 v0.2.6 版本已上架测试专区，支持导入Aegis格式图标包，以及默认自绘制图标。
