### ISSUE TITLE
找不到了

### ISSUE THREAD

**Issue by xiaopixiao** [iamhyc/Aigis#6]
一开始还有呢，后来再想去找就找不到了，请问可以封装一个没签名的安装包吗

**Comment by xiaopixiao** [comment]
我看到前面一个问题说搜索最近使用的元服务可以添加卡片到桌面，确实添加了，这种方法添加的元服务会自动更新版本吗

**Comment by iamhyc** [comment]
> 我看到前面一个问题说搜索最近使用的元服务可以添加卡片到桌面，确实添加了，这种方法添加的元服务会自动更新版本吗

应该不会。

> 一开始还有呢，后来再想去找就找不到了，请问可以封装一个没签名的安装包吗

现在是下载名额满了，看下没什么问题反馈的话，晚上我再增加下限额。

不建议用自签名的包；我这边试了下 商店release 和自签名的debug包是冲突的，要从系统里卸载掉才能安装另一签名的包。

**Comment by xiaopixiao** [comment]
> > 我看到前面一个问题说搜索最近使用的元服务可以添加卡片到桌面，确实添加了，这种方法添加的元服务会自动更新版本吗
> 
> 应该不会。
> 
> > 一开始还有呢，后来再想去找就找不到了，请问可以封装一个没签名的安装包吗
> 
> 现在是下载名额满了，看下没什么问题反馈的话，晚上我再增加下限额。
> 
> 不建议用自签名的包；我这边试了下 商店release 和自签名的debug包是冲突的，要从系统里卸载掉才能安装另一签名的包。

好的，感谢大佬
还有就是桌面卡片的字体大小是不是可以调节一下呢，我现在用的2*2的卡片，感觉查看令牌四个字有点大

**Comment by iamhyc** [comment]
现在的 2x2 有点大吗？我本来是想用下面这个的 🤣 

![图片](https://github.com/user-attachments/assets/c5af27e1-9b23-4318-a93b-cfa311f9c4d2)

这个后面计划做成动态卡片，可以直接查看单个令牌；这个需求优先级会比较低，等主要功能完成后再做。

**Comment by xiaopixiao** [comment]
> 现在的 2x2 有点大吗？我本来是想用下面这个的 🤣
> 
> ![图片](https://private-user-images.githubusercontent.com/9068301/377402245-c5af27e1-9b23-4318-a93b-cfa311f9c4d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjA1NjcsIm5iZiI6MTcyOTE2MDI2NywicGF0aCI6Ii85MDY4MzAxLzM3NzQwMjI0NS1jNWFmMjdlMS05YjIzLTQzMTgtYTkzYi1jZmEzMTFmOWM0ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMTAxNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgwMWNiZDBhNmJjYWI1YTYwNzQ1NGY0OTQwZmU3NWFlODA1NWIwNGU4NTU2MGQ2ODFlYmNhMjU2NzBmNWVmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-i3ErbTdqL5Ixa2dJJ-vhh9OpoSadxw2-M4tHiYqkMs)
> 
> 这个后面计划做成动态卡片，可以直接查看单个令牌；这个需求优先级会比较低，等主要功能完成后再做。

我知道了，是个bug，在桌面和别的卡片堆叠的时候就是你发的这个的样子，不堆叠的时候是小字一横排

**Comment by xiaopixiao** [comment]
> 我知道了，是个bug，在桌面和别的卡片堆叠的时候就是你发的这个的样子，不堆叠的时候是小字一横排
坏了，刚给你发完它就变过来了，那可能是系统bug吧

**Comment by xiaopixiao** [comment]
> 我知道了，是个bug，在桌面和别的卡片堆叠的时候就是你发的这个的样子，不堆叠的时候是小字一横排

坏了，刚给你发完就变过来了，可能是系统bug吧

**Comment by iamhyc** [comment]
这个糟糕的设计在v0.2.2中删掉了；动态卡片的需求计划正式版本之后再做，这个issue就先关掉了。
