### ISSUE TITLE
能不能增加通过totp的链接添加动态码

### ISSUE THREAD

**Issue by yakexi007** [iamhyc/Aigis#7]
你好，现在只能通过扫描二维码增加动态码，希望能加上通过totp的链接增加动态码，谢谢！
类似这种： otpauth://totp/Aliyun:xxxxxx@xxxxxx?secret=xxxxxxxx&issuer=Aliyun
![QQ_1729158801194](https://github.com/user-attachments/assets/b65ae825-bfd9-4456-b463-7c250db2ce37)

**Comment by iamhyc** [comment]
感谢建议！这个UI设计我再考虑下，大概下个测试版本增加功能。

**Comment by iamhyc** [comment]
@yakexi007 Hi，v0.2.2版本已推送测试专区，可以在设置里打开“启动手动输入”，之后首页按钮会变成“加号”，支持输入URI。

本来想顺手把多行批量导入加上，推送的时候忘了加上…… 可以先看下这个实现是否符合需求，之后再改。

**Comment by iamhyc** [comment]
先关掉了，目前测试暂时中止；如果看到这条消息，为了避免当前数据丢失，请留意置顶issue，暂时不要升级5.0系统

https://github.com/iamhyc/Aigis/issues/12
