### ISSUE TITLE
Pad上面只能横屏，显示页面不全，通过二维码迁移会因为页面不全而无法操作，从而导入不进去

### ISSUE THREAD

**Issue by ZYH919** [iamhyc/Aigis#8]

**Comment by iamhyc** [comment]
ok，我这边没有平板测试，我试下模拟器；大概是orientation没配置的原因，预计下个测试版本修正。

**Comment by ZYH919** [comment]
好的，谢谢🙏

**Comment by iamhyc** [comment]
@ZYH919 Hi，v0.2.2版本已推送测试专区，可以试下；目前会根据系统旋转设置改变方向。

**Comment by ZYH919** [comment]
> @ZYH919 Hi，v0.2.2版本已推送测试专区，可以试下；目前会根据系统旋转设置改变方向。

收到
